This is makeindex, version 2.18 [TeX Live 2026] (kpathsea + Thai support).
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file thesis.acr....done (6 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
